Added love godot base, removed weird space above.
love2d-community/awesome-love2d pull request #274
Opened 2024-12-19 19:21 UTC by alejandro-alzate

2025-01-05 06:42 UTC, MikuAuahDark requested changes

2025-01-05 06:42 UTC, MikuAuahDark commented on README.md
> +* [Love-godot-base](https://github.com/rhysuki/love-godot-base) - Godot-flavored template for LÖVE games.
I think this needs its own category, although I'm not sure. It's too big to be considered "helper".

For now, just remove it.

2025-01-06 06:28 UTC, alejandro-alzate commented on README.md
> +* [Love-godot-base](https://github.com/rhysuki/love-godot-base) - Godot-flavored template for LÖVE games.
just resolve conversation?

2025-01-06 06:29 UTC, alejandro-alzate commented on README.md
> +* [Love-godot-base](https://github.com/rhysuki/love-godot-base) - Godot-flavored template for LÖVE games.
how do I allow the edit? I have to do it?

2025-01-08 00:58 UTC, alejandro-alzate commented
PR Dropper in favor of a cleaner one

2025-01-08 00:58 UTC, closed without merging